- hosts: all
  vars:
    - packageName: "apache2"
    - documentRoot: "/var/www/nitesh"
    - webPage: "index.html"
  tasks:
      - name: "Installing Apache Server"
        package:
          name:  "{{ packageName }}"
          state: present

      - name: "Change Document Root"
        copy:
          dest: "/etc/{{ packageName }}/sites-enabled/custom.conf"
          content: "DocumentRoot {{ documentRoot }} \n"
      
      - name: "Create Document Root Folder"
        file:
          path: "{{ documentRoot }}"
          state: directory

      - name: "Copy {{ webPage }} file"
        copy:
          src: "{{ webPage }}"
          dest: "/var/www/nitesh"
        
      - name: "Restart Web Service"
        service:
          name: "{{ packageName }}"
          state: reloaded
          enabled: true
       