version: '3'

services:
  ansible_node1:
#    image: "ansible-image"
    build: .
    container_name: "ansiable_node1"
    ports:
      - 81:80
    privileged: true



  ansible_node2:
#    image: "ansible-image"
    build: .
    container_name: "ansiable_node2"
    ports:
      - 82:80
    privileged: true

