version: '3'

services:
  ansiblehost:
    build: .
    container_name: "ansible_controller"
    ports:
      - 81:80
    volumes:
      - /root/docker-testing-repo/ansible-docke-stack:/root/ansiblerepo
    entrypoint: bash

  
  ansible_node1:
    build: .
    container_name: "ansiable_node1"
    ports:
      - 82:80
    entrypoint: bash

  ansible_node2:
    build: .
    container_name: "ansiable_node2"
    ports:
      - 83:80
    entrypoint: bash