version: "3.8"
#docker run -dit --name nginxtest --network nginxtest -v /root/docker-testing-repo/Docker-Tasks/Docker-Multiphp/nginxdata:/var/www/html/ -v /root/docker-testing-repo/Docker-Tasks/Docker-Multiphp/nginxconf:/etc/nginx/conf.d/ -p 8081:81 -p 8082:82 -p 8083:83 nginx:latest

services:
  nginx:
    image: "nginx:latest"
    container_name: "nginx-server"
    volumes:
      - ./nginxconf:/etc/nginx/conf.d
      - ./nginxdata:/var/www/html
    ports:
      - 81:81
      - 82:82
      - 83:83
    
    